In [1]:
import pandas as pd
import ast
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('TRADES_CopyTr_90D_ROI.csv')

In [3]:

df = df.dropna()

In [4]:
df.isnull().sum()

Port_IDs         0
Trade_History    0
dtype: int64

In [54]:
# Convert 'Trade_History' column entries from string representation of lists to actual lists
df['Trade_History'] = df['Trade_History'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

In [9]:
all_trades = []

In [10]:
for index in df.index:
    port_id = df.at[index, 'Port_IDs'] # Get the Port_ID for the current index
    trades = df.at[index, 'Trade_History']  # Get the trade history for the current index
    
    
    if isinstance(trades, list):
        for trade in trades:
           
            trade_with_port_id = trade.copy()
            trade_with_port_id['Port_ID'] = port_id  
            all_trades.append(trade_with_port_id)  
    else:
        print(f"Skipping non-list trade entry for index {index}: {trades}")

In [11]:
df_trades = pd.DataFrame(all_trades)

In [12]:
df_trades.count()

time                   211277
symbol                 211277
side                   211277
price                  211277
fee                    211277
feeAsset               211277
quantity               211277
quantityAsset          211277
realizedProfit         211277
realizedProfitAsset    211277
baseAsset              211277
qty                    211277
positionSide           211277
activeBuy              211277
Port_ID                211277
dtype: int64

In [13]:
df_trades.head(10)

,time,symbol,side,price,fee,feeAsset,quantity,quantityAsset,realizedProfit,realizedProfitAsset,baseAsset,qty,positionSide,activeBuy,Port_ID
0,1718899656000,SOLUSDT,BUY,132.53700,-0.994027,USDT,1988.05500,USDT,0.0,USDT,SOL,15.0,LONG,True,3925368433214965504
1,1718899618000,DOGEUSDT,BUY,0.12182,-0.279796,USDT,1398.98088,USDT,0.0,USDT,DOGE,11484.0,LONG,False,3925368433214965504
2,1718899618000,DOGEUSDT,BUY,0.12182,-0.039494,USDT,197.47022,USDT,0.0,USDT,DOGE,1621.0,LONG,False,3925368433214965504
3,1718899616000,DOGEUSDT,BUY,0.12182,-0.008284,USDT,16.56752,USDT,0.0,USDT,DOGE,136.0,LONG,True,3925368433214965504
4,1718899616000,DOGEUSDT,BUY,0.12182,-0.046109,USDT,92.21774,USDT,0.0,USDT,DOGE,757.0,LONG,True,3925368433214965504
5,1718899616000,DOGEUSDT,BUY,0.12182,-0.125718,USDT,251.43648,USDT,0.0,USDT,DOGE,2064.0,LONG,True,3925368433214965504
6,1718899616000,DOGEUSDT,BUY,0.12182,-0.021806,USDT,43.61156,USDT,0.0,USDT,DOGE,358.0,LONG,True,3925368433214965504
7,1718899607000,SOLUSDT,BUY,132.58500,-0.159102,USDT,795.51000,USDT,0.0,USDT,SOL,6.0,LONG,False,3925368433214965504
8,1718899607000,SOLUSDT,BUY,132.58500,-0.596633,USDT,1193.26500,USDT,0.0,USDT,SOL,9.0,LONG,True,3925368433214965504
9,1718889684000,FILUSDT,BUY,4.45400,-0.348525,USDT,697.05100,USDT,0.0,USDT,FIL,156.5,LONG,True,3925368433214965504

In [14]:
df_trades.columns

Index(['time', 'symbol', 'side', 'price', 'fee', 'feeAsset', 'quantity',
       'quantityAsset', 'realizedProfit', 'realizedProfitAsset', 'baseAsset',
       'qty', 'positionSide', 'activeBuy', 'Port_ID'],
      dtype='object')

In [15]:
df_trades.to_csv('Final_trade.csv', index=False)

In [16]:
df_trade = pd.read_csv('Final_trade.csv')

In [17]:
df_trade.head()

,time,symbol,side,price,fee,feeAsset,quantity,quantityAsset,realizedProfit,realizedProfitAsset,baseAsset,qty,positionSide,activeBuy,Port_ID
0,1718899656000,SOLUSDT,BUY,132.53700,-0.994027,USDT,1988.05500,USDT,0.0,USDT,SOL,15.0,LONG,True,3925368433214965504
1,1718899618000,DOGEUSDT,BUY,0.12182,-0.279796,USDT,1398.98088,USDT,0.0,USDT,DOGE,11484.0,LONG,False,3925368433214965504
2,1718899618000,DOGEUSDT,BUY,0.12182,-0.039494,USDT,197.47022,USDT,0.0,USDT,DOGE,1621.0,LONG,False,3925368433214965504
3,1718899616000,DOGEUSDT,BUY,0.12182,-0.008284,USDT,16.56752,USDT,0.0,USDT,DOGE,136.0,LONG,True,3925368433214965504
4,1718899616000,DOGEUSDT,BUY,0.12182,-0.046109,USDT,92.21774,USDT,0.0,USDT,DOGE,757.0,LONG,True,3925368433214965504

In [18]:
df_trade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211277 entries, 0 to 211276
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   time                 211277 non-null  int64
 1   symbol               211277 non-null  object
 2   side                 211277 non-null  object
 3   price                211277 non-null  float64
 4   fee                  211277 non-null  float64
 5   feeAsset             211277 non-null  object
 6   quantity             211277 non-null  float64
 7   quantityAsset        211277 non-null  object
 8   realizedProfit       211277 non-null  float64
 9   realizedProfitAsset  211277 non-null  object
 10  baseAsset            211277 non-null  object
 11  qty                  211277 non-null  float64
 12  positionSide         211277 non-null  object
 13  activeBuy            211277 non-null  bool
 14  Port_ID              211277 non-null  int64
dtypes: bool(1), float64(5), int64(2), object(7)
memory usage: 22.8+ MB

In [19]:
# Create a new column to represent the position type based on 'side' and 'positionSide'
df_trade['Position_Type'] = df_trade.apply(lambda x: f"{x['side']}_{x['positionSide']}", axis = 1)

In [20]:
# Calculate the trade value by multiplying quantity by price
df_trade['Trade_value'] = df_trade['quantity'] * df_trade['price']

In [21]:
df_trade.head()

,time,symbol,side,price,fee,feeAsset,quantity,quantityAsset,realizedProfit,realizedProfitAsset,baseAsset,qty,positionSide,activeBuy,Port_ID,Position_Type,Trade_value
0,1718899656000,SOLUSDT,BUY,132.53700,-0.994027,USDT,1988.05500,USDT,0.0,USDT,SOL,15.0,LONG,True,3925368433214965504,BUY_LONG,263490.845535
1,1718899618000,DOGEUSDT,BUY,0.12182,-0.279796,USDT,1398.98088,USDT,0.0,USDT,DOGE,11484.0,LONG,False,3925368433214965504,BUY_LONG,170.423851
2,1718899618000,DOGEUSDT,BUY,0.12182,-0.039494,USDT,197.47022,USDT,0.0,USDT,DOGE,1621.0,LONG,False,3925368433214965504,BUY_LONG,24.055822
3,1718899616000,DOGEUSDT,BUY,0.12182,-0.008284,USDT,16.56752,USDT,0.0,USDT,DOGE,136.0,LONG,True,3925368433214965504,BUY_LONG,2.018255
4,1718899616000,DOGEUSDT,BUY,0.12182,-0.046109,USDT,92.21774,USDT,0.0,USDT,DOGE,757.0,LONG,True,3925368433214965504,BUY_LONG,11.233965

In [23]:
# Aggregate metrics for each Port_ID
Metrics = df_trade.groupby('Port_ID').agg(
    pnl = ('realizedProfit','sum'),
    Win_Positions = ('realizedProfit', lambda x: (x > 0).sum()),
    Total_Positions = ('realizedProfit', 'count'),
).reset_index()

In [24]:
# Calculate ROI
Metrics['ROI'] = (Metrics["pnl"] / (Metrics['pnl'].abs().sum()))* 100

In [25]:
# Calculate winrate
Metrics['Win_rate'] = (Metrics["Win_Positions"] / Metrics['Total_Positions'])* 100

In [26]:
# Calculate return for each trade as realized profit divided by quantity
df_trade['Return'] = df_trade['realizedProfit']/ df_trade['quantity']

In [27]:
df_trade.head()

,time,symbol,side,price,fee,feeAsset,quantity,quantityAsset,realizedProfit,realizedProfitAsset,baseAsset,qty,positionSide,activeBuy,Port_ID,Position_Type,Trade_value,Return
0,1718899656000,SOLUSDT,BUY,132.53700,-0.994027,USDT,1988.05500,USDT,0.0,USDT,SOL,15.0,LONG,True,3925368433214965504,BUY_LONG,263490.845535,0.0
1,1718899618000,DOGEUSDT,BUY,0.12182,-0.279796,USDT,1398.98088,USDT,0.0,USDT,DOGE,11484.0,LONG,False,3925368433214965504,BUY_LONG,170.423851,0.0
2,1718899618000,DOGEUSDT,BUY,0.12182,-0.039494,USDT,197.47022,USDT,0.0,USDT,DOGE,1621.0,LONG,False,3925368433214965504,BUY_LONG,24.055822,0.0
3,1718899616000,DOGEUSDT,BUY,0.12182,-0.008284,USDT,16.56752,USDT,0.0,USDT,DOGE,136.0,LONG,True,3925368433214965504,BUY_LONG,2.018255,0.0
4,1718899616000,DOGEUSDT,BUY,0.12182,-0.046109,USDT,92.21774,USDT,0.0,USDT,DOGE,757.0,LONG,True,3925368433214965504,BUY_LONG,11.233965,0.0

In [30]:

# Calculate Sharpe Ratio for each Port_ID
sharpe_ratio = df_trade.groupby('Port_ID')['Return'].agg(
    mean_return=lambda x: x.mean(),  
    std_return=lambda x: x.std()  
)

In [32]:
risk_free_rate = 0.01

In [33]:
sharpe_ratio['Sharpe_Ratio'] = (sharpe_ratio['mean_return'] - risk_free_rate) / sharpe_ratio['std_return']

In [34]:
Metrics = Metrics.merge(sharpe_ratio[['Sharpe_Ratio']], on='Port_ID', how='left')

In [40]:
# Function to calculate the maximum drawdown from returns
def max_drawdown(returns):
    cumulative_returns = (1 + returns).cumprod()
    peak = cumulative_returns.cummax()
    drawdown = (cumulative_returns - peak) / peak
    return drawdown.min()
# Calculate maximum drawdown for each Port_ID
mdd = df_trade.groupby('Port_ID')['Return'].agg(max_drawdown)
Metrics = Metrics.merge(mdd.rename('MDD'), on='Port_ID')

In [41]:
# Create a score based on weighted contributions of various metrics
Metrics['Score'] = (Metrics['pnl']* 0.5) + (Metrics['Win_Positions'] * 0.3) + (Metrics['ROI'] * 0.2)

In [42]:
# Rank accounts based on the calculated score
Metrics['Rank'] = Metrics['Score'].rank(ascending=False)

In [43]:
Metrics.to_csv('Final_account.csv', index=False)

In [44]:
Metrics.head()

,Port_ID,pnl,Win_Positions,Total_Positions,ROI,Win_rate,Sharpe_Ratio,MDD,Score,Rank
0,3672754654734989568,566.597660,210,474,0.078439,44.303797,0.014430,-0.521129,346.314518,137.0
1,3733192481840423936,2923.977200,553,689,0.404793,80.261248,-0.136288,-0.342743,1627.969558,69.0
2,3768170840939476993,243.668899,6,14,0.033733,42.857143,0.773085,0.000000,123.641196,142.0
3,3784403294629753856,2521.814305,1829,6050,0.349118,30.231405,-0.651515,-0.892999,1809.676976,61.0
4,3786761687746711808,205.021400,37,82,0.028383,45.121951,-0.096206,-0.060229,113.616377,143.0

In [47]:
sorted_metrics = Metrics.sort_values(by='Rank')

In [55]:
Top_20_accounts = sorted_metrics[['Rank','Port_ID', 'Score','pnl', 'Win_Positions', 'Win_rate','ROI', 'Sharpe_Ratio', 'Total_Positions']].head(20)
Top_20_accounts

,Rank,Port_ID,Score,pnl,Win_Positions,Win_rate,ROI,Sharpe_Ratio,Total_Positions
96,1.0,4020204877254599680,36599.321467,71998.855953,1993,32.942149,9.967452,-0.445459,6050
75,2.0,3999240873283311617,21998.215633,42574.473679,2366,52.321981,5.893969,-0.217712,4522
98,3.0,4021669203289716224,13372.797511,26427.331592,528,31.391201,3.658574,-0.600381,1682
50,4.0,3960874214179953664,10154.177423,19567.471286,1233,51.568381,2.708902,-0.332736,2391
17,5.0,3907081197088384000,9770.497509,18015.997370,2540,61.397148,2.494117,0.290320,4137
62,6.0,3986814617275053313,9003.183289,16337.461881,2780,78.221722,2.261742,0.391549,3554
48,7.0,3956076827719377409,9001.170998,16790.012238,2019,51.557712,2.324393,-0.088706,3916
107,8.0,4028701921959171840,8913.088043,17601.401398,373,54.294032,2.436721,-0.825975,687
5,9.0,3788465932399412480,7391.569777,13960.966457,1369,44.607364,1.932743,-0.280950,3069
99,10.0,4022565861939831809,7210.781638,14197.577076,372,52.765957,1.965499,-1.187391,705
63,11.0,3987739404272887297,6646.948275,12464.606315,1381,22.826446,1.725588,-0.267964,6050
27,12.0,3931992636670880512,5916.769905,10374.965290,2430,40.165289,1.436300,-0.154440,6050
84,13.0,4008711265867865600,5699.466031,11298.706390,166,42.131980,1.564182,-1.327305,394
30,14.0,3936410995029308417,5342.852748,10681.514000,6,30.000000,1.478738,0.298094,20
32,15.0,3939318616482048768,4923.365214,9775.389110,118,37.460317,1.353295,-0.236557,315
73,16.0,3998572645139652353,4830.558582,9603.585360,95,35.714286,1.329511,-0.670886,266
51,17.0,3962024093501274881,4758.604928,9314.494060,337,26.472899,1.289490,-1.168020,1273
125,18.0,4031493134338259457,4746.500624,9082.698288,683,36.156697,1.257400,-2.066688,1889
37,19.0,3944088772635000577,4623.155907,7581.491983,2774,45.752928,1.049574,-0.023377,6063
93,20.0,4017263283405469185,4181.080938,7141.366419,2034,33.619835,0.988644,-0.702526,6050